#!/usr/bin/env bash

set -euo pipefail
cd "$( dirname "${BASH_SOURCE[0]}" )"

function print_usage() {
    2>&1 echo "Usage:"
    2>&1 echo "  FOUNDRY=<0.7.9|0.8.8> ${BASH_SOURCE[0]}"
    exit 1
}

if [[ -z "${FOUNDRY+set}" ]]
then
    ## Exit with error:
    2>&1 echo 'Missing environment variable'
    print_usage
fi

if [[ "${FOUNDRY}" != '0.7.9' ]] && [[ "${FOUNDRY}" != '0.8.8' ]]
then
    ## Exit with error:
    2>&1 echo "Unknown Foundry version ‘${FOUNDRY}’"
    print_usage
fi

## Install updated types:
npm install \
    --no-audit --no-progress --silent \
    "@league-of-foundry-developers/foundry-vtt-types@fvtt-${FOUNDRY}"

## Switch FoundryCompat:
echo "export * from './foundry-compat-${FOUNDRY}'" > src/helpers/foundry-compat.ts

## Print success:
echo "Switched Foundry version to ‘${FOUNDRY}’"
