name: CI

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: git checkout
        uses: actions/checkout@v2

      - name: npm install
        run: npm install

      - name: Run unit tests
        run: npm test

      - name: Compile
        run: NODE_ENV=production npx rollup -c
