name: Publish

on:
  release:
    types: [created, edited]

jobs:
  publish_zip:
    runs-on: ubuntu-latest

    steps:
      - name: Determine filename from release tag
        run: |
          set -eu
          PREFIX='refs/tags/v'

          if [[ "${GITHUB_REF}" != ${PREFIX}* ]]; then
            2>&1 echo "Release tag ‘${GITHUB_REF}’ does not start with ‘${PREFIX}’"
            false
          fi

          echo "ZIP_NAME=\"wor-${GITHUB_REF:${#PREFIX}}.zip\"" >> $GITHUB_ENV

      - name: git checkout
        uses: actions/checkout@v2

      - name: npm install
        run: npm install

      - name: Compile
        run: NODE_ENV=production npx rollup -c

      - name: Create ZIP
        run: |
          set -eu
          shopt -s globstar
          zip "${ZIP_NAME}" dist/wor.js dist/wor.css src/**/*.hbs

      - name: Upload ZIP
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{ env.ZIP_NAME }}
          tag: ${{ env.GITHUB_REF }}
          overwrite: true

      # - name: Update manifest
      #   uses: jossef/action-set-json-field@v1
      #   with:
      #     file: system.json
      #     field: downloadUrl
      #     value: ${{ format('https://github.com/fishmilk-society/wor/releases/download/v${0}/wor-${0}.zip', env.VERSION) }}
