name: Publish

on:
  release:
    types: [created, edited]

jobs:
  job:
    runs-on: ubuntu-latest

    steps:
      - name: Check Ref is well-formed
        run: |
          set -eu
          if [[ "${GITHUB_REF}" != refs/tags/v* ]]; then
            2>&1 echo "Release tag ‘${GITHUB_REF}’ does not start with ‘refs/tags/v’"
            false
          fi

      - name: Parse Ref
        id: tag_parser
        run: |
          set -eu
          echo "WOR_VERSION=${GITHUB_REF:11}" >> $GITHUB_ENV

      - name: git checkout
        uses: actions/checkout@v2

      - name: Update version in package.json
        uses: jossef/action-set-json-field@v1
        with:
          file: package.json
          field: version
          value: ${{ env.WOR_VERSION }}

      - name: Update version in manifest
        uses: jossef/action-set-json-field@v1
        with:
          file: system.json
          field: version
          value: ${{ env.WOR_VERSION }}

      - name: Update download URL in manifest
        uses: jossef/action-set-json-field@v1
        with:
          file: system.json
          field: download
          value: ${{ format('https://github.com/fishmilk-society/wor/releases/download/v{0}/wor-{0}.zip', env.WOR_VERSION) }}

      - name: npm install
        run: npm install

      - name: Compile
        run: make

      - name: Create ZIP
        run: |
          set -eu
          shopt -s globstar
          zip wor.zip system.json template.json dist/wor.js dist/wor.css src/**/*.hbs

      - name: Upload ZIP
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ github.token }}
          file: wor.zip
          tag: ${{ github.ref }}
          asset_name: ${{ format('wor-{0}.zip', env.WOR_VERSION) }}
          overwrite: true

      - name: Upload manifest
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ github.token }}
          file: system.json
          tag: ${{ github.ref }}
          asset_name: ${{ format('wor-{0}.json', env.WOR_VERSION) }}
          overwrite: true

      - name: Configure Git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "<>"

      - name: Publish to temporary branch
        run: |
          git checkout -b "tmp-v${WOR_VERSION}"
          git add package.json package-lock.json system.json
          git commit -m "Publish v${WOR_VERSION}"
          git push --force origin HEAD

      - name: Publish to main
        run: |
          git push origin HEAD:main
