name: Publish

on:
  release:
    types: [created, edited]

jobs:
  tag_parser:
    runs-on: ubuntu-latest

    outputs:
      version: ${{ steps.main.outputs.version }}

    steps:
      - name: Check Ref is well-formed
        run: |
          set -eu
          if [[ "${GITHUB_REF}" != refs/tags/v* ]]; then
            2>&1 echo "Release tag ‘${GITHUB_REF}’ does not start with ‘refs/tags/v’"
            false
          fi

      - name: Determine filenames from Ref
        id: main
        run: |
          set -eu
          echo "::set-output name=version::${GITHUB_REF:11}"

  publish_zip:
    runs-on: ubuntu-latest
    needs: tag_parser

    outputs:
      url: ${{ steps.upload.outputs.browser_download_url }}

    steps:
      - name: git checkout
        uses: actions/checkout@v2

      - name: npm install
        run: npm install

      - name: Compile
        run: NODE_ENV=production npx rollup -c

      - name: Create ZIP
        run: |
          set -eu
          shopt -s globstar
          zip wor.zip system.json template.json dist/wor.js dist/wor.css src/**/*.hbs

      - name: Upload ZIP
        id: upload
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ github.token }}
          file: wor.zip
          tag: ${{ github.ref }}
          asset_name: ${{ format('wor-{0}.zip', needs.tag_parser.outputs.version) }}
          overwrite: true

  publish_manifest:
    runs-on: ubuntu-latest
    needs: [tag_parser, publish_zip]

    steps:
      - name: git checkout
        uses: actions/checkout@v2

      - name: Specify ZIP in manifest
        uses: jossef/action-set-json-field@v1
        with:
          file: system.json
          field: downloadUrl
          value: ${{ needs.publish_zip.outputs.url }}

      - name: Upload manifest
        id: upload
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ github.token }}
          file: system.json
          tag: ${{ github.ref }}
          asset_name: ${{ format('wor-{0}.json', needs.tag_parser.outputs.version) }}
          overwrite: true
